export enum ConfettiOptions {
    MIN_CONFETTI_ANGLE = 10,
    MAX_CONFETTI_ANGLE = 170,
    MIN_CONFETTI_SPREAD = 50,
    MAX_CONFETTI_SPREAD = 70,
    MIN_CONFETTI_PARTICLE_COUNT = 50,
    MAX_CONFETTI_PARTICLE_COUNT = 100,
    WINNER_CONFETTI_COUNT = 5,
    WINNER_CONFETTI_DELAY = 1000,
}
