const FACTOR = 9000;
const MAXIMUM_CODE_LENGTH = 4;
const COUNTDOWN_TIME = 5;
const COOLDOWN_TIME = 3;
const BONUS_FACTOR = 0.2;
const MULTIPLICATION_FACTOR = 100;
const MINIMUM_QUESTIONS = 5;
const HOST_USERNAME = 'Organisateur';
const FREE_ANSWER_MAX_LENGTH = 200;
const LONG_ANSWER_TIME = 60;
const HISTOGRAM_UPDATE_TIME_SECONDS = 5;
const HISTOGRAM_UPDATE_TIME_MS = 5000;
const PANIC_ALERT_DELAY = 1000;
const MAX_REWARD = 100;
const MIN_REWARD = 50;

export {
    BONUS_FACTOR,
    COOLDOWN_TIME,
    COUNTDOWN_TIME,
    FACTOR,
    FREE_ANSWER_MAX_LENGTH,
    HISTOGRAM_UPDATE_TIME_MS,
    HISTOGRAM_UPDATE_TIME_SECONDS,
    HOST_USERNAME,
    LONG_ANSWER_TIME,
    MAX_REWARD,
    MAXIMUM_CODE_LENGTH,
    MIN_REWARD,
    MINIMUM_QUESTIONS,
    MULTIPLICATION_FACTOR,
    PANIC_ALERT_DELAY,
};
