const FACTOR = 9000;
const MAXIMUM_CODE_LENGTH = 4;
const COUNTDOWN_TIME = 5;
const COOLDOWN_TIME = 3;
const BONUS_FACTOR = 0.2;
const MULTIPLICATION_FACTOR = 100;
const MINIMUM_QUESTIONS = 5;
const HOST_USERNAME = 'Organisateur';
const FREE_ANSWER_MAX_LENGTH = 200;
const LONG_ANSWER_TIME = 60;
const HISTOGRAM_UPDATE_TIME_SECONDS = 5;
const HISTOGRAM_UPDATE_TIME_MS = 5000;
const PANIC_ALERT_DELAY = 1000;

export {
    LONG_ANSWER_TIME,
    FREE_ANSWER_MAX_LENGTH,
    HOST_USERNAME,
    BONUS_FACTOR,
    FACTOR,
    MAXIMUM_CODE_LENGTH,
    COOLDOWN_TIME,
    COUNTDOWN_TIME,
    MULTIPLICATION_FACTOR,
    HISTOGRAM_UPDATE_TIME_SECONDS,
    HISTOGRAM_UPDATE_TIME_MS,
    MINIMUM_QUESTIONS,
    PANIC_ALERT_DELAY,
};
