export enum MatchEvents {
    JoinRoom = 'joinRoom',
    CreateRoom = 'createRoom',
    AddPlayer = 'addPlayer',
    ToggleLock = 'toggleLock',
    BanUsername = 'banUsername',
    KickPlayer = 'kickPlayer',
    SendPlayersData = 'sendPlayersData',
    FetchPlayersData = 'fetchPlayersData',
    StartMatch = 'startMatch',
    MatchStarting = 'matchStarting',
    CheaterModeMatchStarting = 'CheaterModeMatchStarting',
    BeginQuiz = 'beginQuiz',
    GoToNextQuestion = 'goToNextQuestion',
    StartCooldown = 'startCooldown',
    CurrentAnswers = 'currentAnswers',
    Winner = 'winner',
    RouteToResultsPage = 'routeToResultsPage',
    HostQuitMatch = 'hostQuitMatch',
    Disconnect = 'disconnectFromRoom',
    Error = 'error',
    GetAllMatches = 'getAllMatches',
    ReturnAllMatches = 'returnAllMatches',
    StartMatchCheaterMode = 'startMatchCheaterMode',
    SendCheater = 'sendCheater',
}
