const MIN_CHOICES_NUMBER = 2;
const MAX_CHOICES_NUMBER = 4;
const MIN_POINTS = 10;
const MAX_POINTS = 100;
const STEP_POINTS = 10;
const MIN_DURATION = 10;
const MAX_DURATION = 60;
const MIN_QUESTIONS_NUMBER = 1;

export { MAX_CHOICES_NUMBER, MAX_DURATION, MAX_POINTS, MIN_CHOICES_NUMBER, MIN_DURATION, MIN_POINTS, MIN_QUESTIONS_NUMBER, STEP_POINTS };
