package com.example.polyquiz.constants

enum class MatchEvents(val value: String) {
    JOIN_ROOM("joinRoom"),
    CREATE_ROOM("createRoom"),
    ADD_PLAYER("addPlayer"),
    TOGGLE_LOCK("toggleLock"),
    BAN_USERNAME("banUsername"),
    KICK_PLAYER("kickPlayer"),
    SEND_PLAYERS_DATA("sendPlayersData"),
    FETCH_PLAYERS_DATA("fetchPlayersData"),
    START_MATCH("startMatch"),
    MATCH_STARTING("matchStarting"),
    BEGIN_QUIZ("beginQuiz"),
    GO_TO_NEXT_QUESTION("goToNextQuestion"),
    START_COOLDOWN("startCooldown"),
    CURRENT_ANSWERS("currentAnswers"),
    WINNER("winner"),
    ROUTE_TO_RESULTS_PAGE("routeToResultsPage"),
    HOST_QUIT_MATCH("hostQuitMatch"),
    DISCONNECT("disconnectFromRoom"),
    ERROR("error"),
    GET_ALL_MATCHES("getAllMatches"),
    RETURN_ALL_MATCHES ("returnAllMatches"),
    START_MATCH_CHEATER_MODE("startMatchCheaterMode"),
    SEND_CHEATER("sendCheater"),
    VOTE_ON_CHEATER("voteOnCheater"),
    SHOW_VOTING_DIALOG("showVotingDialog"),
    SEND_VOTES_RESULTS("sendVotesResults"),
    SEND_BACK_VOTES_RESULTS("sendBackVotesResults"),
    SEND_UPDATED_SCORES("sendUpdatedScores"),
    CHEATER_MODE_MATCH_STARTING("CheaterModeMatchStarting"),
}
